# Generated by Django 3.2.5 on 2021-09-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosmodel',
            name='hora',
            field=models.TimeField(default='08:00'),
        ),
    ]
