# Generated by Django 3.2.5 on 2021-09-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_eventosmodel_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventosmodel',
            options={'ordering': ['-fecha_evento'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
