# Generated by Django 3.2.5 on 2021-10-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_eventosmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventosmodel',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
