# Generated by Django 3.2.5 on 2021-10-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_eventosmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosmodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
