# Generated by Django 3.1 on 2020-10-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
