# Generated by Django 3.1 on 2020-09-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20200923_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
