# Generated by Django 3.1 on 2021-02-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semana', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['date_day'], 'verbose_name': 'Actividad del Mes', 'verbose_name_plural': 'Actividades'},
        ),
    ]
