# Generated by Django 3.1 on 2021-02-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria')),
                ('nombre', models.CharField(max_length=50)),
                ('created', models.DateField()),
            ],
            options={
                'verbose_name': 'Imagenes',
            },
        ),
    ]
