# Generated by Django 3.1 on 2021-02-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'ordering': ['-created'], 'verbose_name': 'Imagenes'},
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
