# Generated by Django 3.1 on 2021-02-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20210209_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'ordering': ['-created'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Imagenes'},
        ),
    ]
